version = 1

[[annotations]]
path = [
 ".circleci/config.yml",
 ".credo.exs",
 ".formatter.exs",
 ".github/CODEOWNERS",
 ".github/dependabot.yml",
 ".gitignore",
 "CHANGELOG.md",
 "NOTICE",
 "REUSE.toml",
 "mix.exs",
 "mix.lock"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 Frank Hunleth"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
 "test/fixtures/ssh_host_rsa_key",
 "test/fixtures/ssh_host_rsa_key.pub"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"
